"""Autonomous follow-up, lifecycle, progress, reranking, and checkpoints.

Revision ID: 022_autonomous_engagement
Revises: 021_outcome_memory
"""
from alembic import op
import sqlalchemy as sa
revision="022_autonomous_engagement"; down_revision="021_outcome_memory"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("conversation_sync_jobs", sa.Column("id",sa.Integer(),primary_key=True),sa.Column("conversation_id",sa.String(128),nullable=False,unique=True),sa.Column("status",sa.String(32),nullable=False,server_default="PENDING"),sa.Column("retry_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("last_attempt_at",sa.DateTime()),sa.Column("completed_at",sa.DateTime()),sa.Column("error_message",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_index("ix_conversation_sync_jobs_conversation_id","conversation_sync_jobs",["conversation_id"]); op.create_index("ix_conversation_sync_jobs_status","conversation_sync_jobs",["status"])
    op.create_table("followup_tasks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("candidate_id",sa.String(128),nullable=False),sa.Column("job_id",sa.Integer(),sa.ForeignKey("jobs.id",ondelete="SET NULL")),sa.Column("conversation_id",sa.String(128),nullable=False),sa.Column("action",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="PENDING"),sa.Column("scheduled_for",sa.DateTime(),nullable=False),sa.Column("executed_at",sa.DateTime()),sa.Column("result",sa.JSON()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("candidate_id","conversation_id","action",name="uq_followup_conversation_action"))
    for c in ("candidate_id","job_id","conversation_id","action","status","scheduled_for"): op.create_index(f"ix_followup_tasks_{c}","followup_tasks",[c])
    op.create_table("application_lifecycle",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("candidate_id",sa.String(128),nullable=False),sa.Column("job_id",sa.Integer(),sa.ForeignKey("jobs.id",ondelete="CASCADE"),nullable=False),sa.Column("state",sa.String(32),nullable=False,server_default="DISCOVERED"),sa.Column("reason",sa.Text(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False,server_default="0.5"),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("candidate_id","job_id",name="uq_application_lifecycle_candidate_job"))
    for c in ("candidate_id","job_id","state"): op.create_index(f"ix_application_lifecycle_{c}","application_lifecycle",[c])
    op.create_table("career_progress_metrics",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("candidate_id",sa.String(128),nullable=False),sa.Column("dimension",sa.String(64),nullable=False),sa.Column("dimension_value",sa.String(512),nullable=False),sa.Column("engagement_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("conversion_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("conversion_rate",sa.Float(),nullable=False,server_default="0"),sa.Column("calculated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("candidate_id","dimension","dimension_value",name="uq_career_progress_dimension"))
    op.create_index("ix_career_progress_metrics_candidate_id","career_progress_metrics",["candidate_id"]); op.create_index("ix_career_progress_metrics_dimension","career_progress_metrics",["dimension"])
    op.create_table("opportunity_reranking_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("candidate_id",sa.String(128),nullable=False),sa.Column("job_id",sa.Integer(),sa.ForeignKey("jobs.id",ondelete="CASCADE"),nullable=False),sa.Column("existing_match_score",sa.Float(),nullable=False),sa.Column("memory_affinity_score",sa.Float(),nullable=False),sa.Column("outcome_success_score",sa.Float(),nullable=False),sa.Column("final_opportunity_ranking",sa.Float(),nullable=False),sa.Column("explanation",sa.JSON()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("candidate_id","job_id",name="uq_reranking_candidate_job"))
    for c in ("candidate_id","job_id","final_opportunity_ranking"): op.create_index(f"ix_opportunity_reranking_records_{c}","opportunity_reranking_records",[c])
    op.create_table("langgraph_checkpoints",sa.Column("thread_id",sa.String(256),primary_key=True),sa.Column("thread_ts",sa.String(128),primary_key=True),sa.Column("checkpoint",sa.LargeBinary(),nullable=False),sa.Column("metadata",sa.LargeBinary(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()))
def downgrade():
    for t in ("langgraph_checkpoints","opportunity_reranking_records","career_progress_metrics","application_lifecycle","followup_tasks","conversation_sync_jobs"): op.drop_table(t)
